- name: snap | install | classic packages
  tags: packages, snap
  become: yes
  snap:
    classic: yes
    state: present
    name: {{ item }}
  with_items: {{ snap }}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
