---
- name: curl | install
  tags: curl
  become: '{{ ansible_distribution != "MacOSX" }}'
  package:
    state: present
    name: curl

- name: curl | install | .curlrc
  tags: curl, .curlrc, dotfile
  copy:
    src: files/curl/curlrc
    dest: '{{ ansible_env.HOME }}/.curlrc'
    owner: '{{ ansible_env.USER }}'
