---
- include_vars: "defaults/main.yml"
  tags: always

- hosts: localhost
  roles:
    - role: macos
    - role: cli
    # - role: pip
    - role: homebrew_cask

    - role: apt
    - role: snap

    - role: ack
    - role: curl
    - role: git
    - role: tmux
    - role: tmuxinator
    - role: vim
    - role: wget
