- name: apt | install | packages
  tags: packages, apt
  become: yes
  apt:
    state: latest
    name: {{ item }}
  with_items: {{ apt }}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
