- name: Copying aliases into global aliases folder'
  tags: macos, finder, aliases 
  copy:
    src: files/aliases/
    dest: '{{ SHELL_ALIASES_DIR }}/'
    owner: '{{ ansible_env.USER }}'

- name: "macos: finder: Enables ethernet for AirDrop"
  tags: macos, finder, airdrop
  command: defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1

- name: "macos: finder: show all filename extensions"
  tags: macos, finder, extensions
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: "macos: don't ask confirmation for change extension"
  tags: macos, finder, extensions
  command: defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

- name: "macos: finder: when performing a search, search the current folder by default"
  tags: macos, finder, search
  command: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

- name: "macos: finder: Avoid creating .DS_Store files on network volumes"
  tags: macos, finder, DS_Store
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: "macos: finder: show the ~/Library folder"
  tags: macos, finder, library
  command: chflags nohidden ~/Library

- name: "macos: finder: column view as default"
  tags: macos, finder
  command: defaults write com.apple.Finder FXPreferredViewStyle clmvx

- name: "macos: install mysides to manage favorites"
  tags: macos, finder, favorites
  become: no
  homebrew_cask:
    state: present
    name: mysides

- name: "macos: finder: favorites: development dir"
  tags: macos, finder, favorites
  command: "mysides append Development {{ DEVELOPMENT_DIR }}"
