- name: "macos: keyboard: set initial key repeat"
  tags: macos, keyboard, key-repeat
  command: defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)

- name: "macos: keyboard: set key repeat"
  tags: macos, keyboard, key-repeat
  command: defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)
