- name: macos
  tags: macos
  block:
  - name: "macos: screenshots: downloads folder"
    tags: macos, screenshots, downloads
    command: defaults write com.apple.screencapture location ~/Downloads

  - import_tasks: appearance.yml
  - import_tasks: dock.yml
  - import_tasks: finder.yml
  - import_tasks: keyboard.yml
  - import_tasks: quicklook.yml
  - import_tasks: screenshot.yml
  - import_tasks: touch.yml

  when: ansible_distribution == 'MacOSX'
