- name: "macos: quicklook: install plugins"
  tags: macos, quicklook
  homebrew_cask:
    state: present
    name: "{{ item }}"
  with_items: "{{ quicklook_plugins }}"

- name: "macos: quicklook: plugin permissions"
  tags: macos, quicklook
  become_user: '{{ ansible_env.USER }}'
  shell: 'xattr -cr ~/Library/QuickLook/*.qlgenerator'
