- debug:
    msg: "System {{ ansible_distribution }}"

- name: homebrew_cask | install | packages
  tags: packages, homebrew, cask
  become: no
  homebrew:
    state: present
    name: "{{ item }}"
  with_items: "{{ homebrew_cask }}"
  when: "{{ ansible_distribution == 'MacOSX' }}"
