- name: homebrew
  tags: packages, homebrew
  become: no
  homebrew:
    state: present
    name:
      - docker
      - docker-compose
      - ffmpeg
      - wget

- name: homebrew_cask | install | packages
  tags: packages, homebrew_cask
  become: no
  homebrew:
    state: present
    name:
      - 1password
      - cyberduck
      - firefox
      - gitkraken
      - gitup
      - google-chrome
      - iterm2
      - macdown
      - microsoft-teams
      - notion
      - opera
      - postman
      - slack
      - tidal
      - vlc
      - whatsapp
