- name: iterm2
  tags: iterm2, macos
  block:
    - name: install iterm2 and fonts
      become: false
      homebrew_cask:
        state: present
        name:
          - iterm2
          - font-fira-code-nerd-font
          - font-hack
          - font-jetbrains-mono
          - font-hasklug-nerd-font

    - name: clone iterm2 dracula theme
      git:
        repo: https://github.com/dracula/iterm.git
        dest: ~/.config/dracula/iterm/
        clone: yes

    - name: install dracula theme
      shell: open ~/.config/dracula/

  when: ansible_distribution == 'MacOSX'
