- name: vim | install
  tags: vim
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - vim
      - neovim

- name: vim } directory | config nvim
  file:
    path: '{{ LUNARVIM_DIR }}'
    state: directory
    owner: '{{ ansible_env.USER }}'

- name: vim | lvim | install
  tags: vim, lvim
  shell: 'bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) --yes'

- name: vim | lvim | config
  tags: vim, lvim
  copy:
    src: files/config.lua
    dest: '{{ LUNARVIM_DIR }}/config.lua'
    owner: '{{ ansible_env.USER }}'

- name: vim | install | aliases
  tags: vim, lvim
  copy:
    src: files/aliases
    dest: '{{ SHELL_ALIASES_DIR }}/vim'
    owner: '{{ ansible_env.USER }}'
