- name: vim | install
  tags: vim
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - vim
      - neovim

- name: create nvim directory
  file:
    path: '{{NVIM_DIR}}'
    state: directory
    owner: '{{ USER }}'

- name: vim | install | .vimrc
  tags: vim, dotfile
  copy:
    src: vim/vimrc
    dest: '{{ NVIM_DIR }}/init.vim'
    owner: '{{ USER }}'

- name: vim | plugin | coc dependecies
  tags: vim, plugin, coc
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - python3
      - python3-pip

- name: vim | plugin | fix coc python error
  tags: vim, plugin, coc, fix
  shell: 'python3 -m pip install --user --upgrade pynvim'


- name: vim | install | .ctags
  tags: vim, dotfile, ctags
  copy:
    src: vim/ctags
    dest: '{{ HOME_DIR }}/.ctags'
    owner: '{{ USER }}'

- name: vim | install | aliases
  tags: vim, aliases
  copy:
    src: files/vim/aliases
    dest: '{{ ALIASES_DIR }}/vim'
    owner: '{{ USER }}'
