- name: tmuxinator | install
  tags: tmuxinator
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - tmuxinator

- name: tmuxinator | install | boilerplate projects
  tags: tmuxinator
  copy:
    src: files/projects/
    dest: '{{ TMUXINATOR_DIR }}'
    owner: '{{ ansible_env.USER }}'

- name: tmuxinator | install | aliases
  tags: tmuxinator, aliases
  copy:
    src: files/aliases
    dest: '{{ SHELL_ALIASES_DIR }}/tmuxinator'
    owner: '{{ ansible_env.USER }}'
