- include_vars: "cli.yml"
  tags: always

- name: cli | install
  tags: cli, install
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: latest
    name: "{{ item }}"
  with_items: "{{ cli }}"
